# Generated by Django 2.1.5 on 2019-02-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.PositiveIntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField(default='Bot')),
                ('content', models.TextField(default='Bla bla bla')),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
